# Generated by Django 6.0.1 on 2026-01-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_book_authors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
