# Generated by Django 6.0.1 on 2026-01-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_table_alter_review_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
