"""make age nullable

Revision ID: 8cd55adb6fb2
Revises: 539e3a7b0568
Create Date: 2025-11-05 15:13:18.712446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8cd55adb6fb2'
down_revision: Union[str, Sequence[str], None] = '539e3a7b0568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
