"""make profile bio not nullable

Revision ID: 2c42d4f00e37
Revises: 668fd76dc07d
Create Date: 2025-09-29 18:55:10.915030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c42d4f00e37'
down_revision: Union[str, Sequence[str], None] = '668fd76dc07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'bio',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
