"""add post_likes, comment_likes tables

Revision ID: dd09b2a7b556
Revises: 2c42d4f00e37
Create Date: 2025-10-01 02:37:46.478257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd09b2a7b556'
down_revision: Union[str, Sequence[str], None] = '2c42d4f00e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
